pvis-links-checker/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'IndexController@index']);
Route::resource('links', 'IndexController');

pvis-links-checker/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

pvis-links-checker/app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use App\Model\Link;

/**
 * Class IndexController
 * @package App\Http\Controllers
 */
class IndexController extends Controller
{
    /**
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $links = Link::with('diffs')->get();

        return response()->view('index_admin', compact('links'));
    }

    public function show(Link $link)
    {
        $link->load([
            'diffs' => function ($query) {
                $query->orderBy('created_at', 'desc');
            }
        ]);

        return response()->view('show_admin', compact('link'));
    }
}

pvis-links-checker/resources/views/index_admin.blade.php
@extends('layout')

@section('content')
    <article class="content dashboard-page">
        <div class="title-block">
            <h1 class="title"> Static Tables </h1>
            <p class="title-description"> When blocks aren't enough </p>
        </div>
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <section class="example">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Url</th>
                                        <th>Poslední kontrola</th>
                                        <th>Poslední změna</th>
                                        <th>Shoda %</th>
                                        <th>Rozdíl %</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($links as $link)
                                        <tr>
                                            <th scope="row">{{ $link->id }}</th>
                                            <td>{{ $link->url }}</td>
                                            <td>{{ $link->checked_at->format('j. n. Y H:i:s') }}</td>
                                            <td>{{ $link->diffs->last() ? $link->diffs->last()->created_at->format('j. n. Y H:i:s') : 'n/a' }}</td>
                                            <td>{{ $link->diffs->last() ? $link->diffs->last()->similarity : 0 }}</td>
                                            <td>{{ $link->diffs->last() ? $link->diffs->last()->difference : 0 }}</td>
                                            <td>
                                                <a href="{{ route('links.show', $link) }}"><i class="fa fa-search"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </article>
@endsection

pvis-links-checker/resources/views/layout.blade.php
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> ModularAdmin - Free Dashboard Theme | HTML Version </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->
    <link rel="stylesheet" href="{{ asset('css/vendor.css') }}">
    <link rel="stylesheet" id="theme-style" href="{{ asset('css/app.css') }}">

    <style type="text/css">
        .diff {
            width:100%;
        }

        .diff td{
            padding:0 0.667em;
            vertical-align:top;
            white-space:pre;
            white-space:pre-wrap;
            font-family:Consolas,'Courier New',Courier,monospace;
            font-size:0.75em;
            line-height:1.333;
        }

        .diff span{
            display:block;
            min-height:1.333em;
            margin-top:-1px;
            padding:0 3px;
        }

        * html .diff span{
            height:1.333em;
        }

        .diff span:first-child{
            margin-top:0;
        }

        .diffDeleted span{
            border:1px solid rgb(255,192,192);
            background:rgb(255,224,224);
        }

        .diffInserted span{
            border:1px solid rgb(192,255,192);
            background:rgb(224,255,224);
        }

        #toStringOutput{
            margin:0 2em 2em;
        }

    </style>

</head>

<body>

<div class="main-wrapper">
    <div class="app" id="app">
        @include('layouts.header')
        @include('layouts.left-bar')
        @yield('content')
        @include('layouts.footer')
    </div>
</div>

<script src="{{ asset('js/vendor.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

pvis-links-checker/resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="footer-block buttons"></div>
    <div class="footer-block author"></div>
</footer>

pvis-links-checker/resources/views/layouts/header.blade.php
<header class="header">
    <div class="header-block header-block-collapse hidden-lg-up">
        <button class="collapse-btn" id="sidebar-collapse-btn">
            <i class="fa fa-bars"></i>
        </button>
    </div>
    <div class="header-block header-block-search hidden-sm-down">
        <form role="search">
            <div class="input-container"><i class="fa fa-search"></i> <input type="search" placeholder="Search">
                <div class="underline"></div>
            </div>
        </form>
    </div>
    <div class="header-block header-block-buttons"></div>
    <div class="header-block header-block-nav">
        <ul class="nav-profile">
            <li class="notifications new">
                <a href="" data-toggle="dropdown"> <i class="fa fa-bell-o"></i> <sup>
                        <span class="counter">8</span>
                    </sup> </a>
                <div class="dropdown-menu notifications-dropdown-menu">
                    <ul class="notifications-container">
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('assets/faces/3.jpg')"></div>
                                </div>
                                <div class="body-col">
                                    <p><span class="accent">Zack Alien</span> pushed new commit: <span
                                                class="accent">Fix page load performance issue</span>. </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('assets/faces/5.jpg')"></div>
                                </div>
                                <div class="body-col">
                                    <p><span class="accent">Amaya Hatsumi</span> started new task: <span
                                                class="accent">Dashboard UI design.</span>. </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('assets/faces/8.jpg')"></div>
                                </div>
                                <div class="body-col">
                                    <p><span class="accent">Andy Nouman</span> deployed new version of <span
                                                class="accent">NodeJS REST Api V3</span></p>
                                </div>
                            </a>
                        </li>
                    </ul>
                    <footer>
                        <ul>
                            <li><a href="">
                                    View All
                                </a></li>
                        </ul>
                    </footer>
                </div>
            </li>
            <li class="profile dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">
                    <div class="img"
                         style="background-image: url('https://avatars3.githubusercontent.com/u/3959008?v=3&s=40')"></div>
                    <span class="name">
    			      John Doe
    			    </span> </a>
                <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="#"> <i class="fa fa-user icon"></i> Profile </a>
                    <a class="dropdown-item" href="#"> <i class="fa fa-bell icon"></i> Notifications </a>
                    <a class="dropdown-item" href="#"> <i class="fa fa-gear icon"></i> Settings </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html"> <i class="fa fa-power-off icon"></i> Logout </a>
                </div>
            </li>
        </ul>
    </div>
</header>

pvis-links-checker/resources/views/layouts/left-bar.blade.php
<aside class="sidebar">
    <div class="sidebar-container">
        <div class="sidebar-header">
            <div class="brand">
                <div class="logo"><span class="l l1"></span> <span class="l l2"></span> <span
                            class="l l3"></span> <span class="l l4"></span> <span class="l l5"></span></div>
                Modular Admin
            </div>
        </div>
        <nav class="menu">
            <ul class="nav metismenu" id="sidebar-menu">
                <li class="active">
                    <a href="index.html"> <i class="fa fa-home"></i> Dashboard </a>
                </li>
                <li>
                    <a href=""> <i class="fa fa-th-large"></i> Items Manager <i class="fa arrow"></i> </a>
                    <ul>
                        <li><a href="items-list.html">
                                Items List
                            </a></li>
                        <li><a href="item-editor.html">
                                Item Editor
                            </a></li>
                    </ul>
                </li>
                <li>
                    <a href=""> <i class="fa fa-bar-chart"></i> Charts <i class="fa arrow"></i> </a>
                    <ul>
                        <li><a href="charts-flot.html">
                                Flot Charts
                            </a></li>
                        <li><a href="charts-morris.html">
                                Morris Charts
                            </a></li>
                    </ul>
                </li>
                <li>
                    <a href=""> <i class="fa fa-table"></i> Tables <i class="fa arrow"></i> </a>
                    <ul>
                        <li><a href="static-tables.html">
                                Static Tables
                            </a></li>
                        <li><a href="responsive-tables.html">
                                Responsive Tables
                            </a></li>
                    </ul>
                </li>
                <li>
                    <a href="forms.html"> <i class="fa fa-pencil-square-o"></i> Forms </a>
                </li>
                <li>
                    <a href=""> <i class="fa fa-desktop"></i> UI Elements <i class="fa arrow"></i> </a>
                    <ul>
                        <li><a href="buttons.html">
                                Buttons
                            </a></li>
                        <li><a href="cards.html">
                                Cards
                            </a></li>
                        <li><a href="typography.html">
                                Typography
                            </a></li>
                        <li><a href="icons.html">
                                Icons
                            </a></li>
                        <li><a href="grid.html">
                                Grid
                            </a></li>
                    </ul>
                </li>
                <li>
                    <a href=""> <i class="fa fa-file-text-o"></i> Pages <i class="fa arrow"></i> </a>
                    <ul>
                        <li><a href="login.html">
                                Login
                            </a></li>
                        <li><a href="signup.html">
                                Sign Up
                            </a></li>
                        <li><a href="reset.html">
                                Reset
                            </a></li>
                        <li><a href="error-404.html">
                                Error 404 App
                            </a></li>
                        <li><a href="error-404-alt.html">
                                Error 404 Global
                            </a></li>
                        <li><a href="error-500.html">
                                Error 500 App
                            </a></li>
                        <li><a href="error-500-alt.html">
                                Error 500 Global
                            </a></li>
                    </ul>
                </li>
                <li>
                    <a href="https://github.com/modularcode/modular-admin-html"> <i
                                class="fa fa-github-alt"></i> Theme Docs </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>
<div class="sidebar-overlay" id="sidebar-overlay"></div>

pvis-links-checker/resources/views/show_admin.blade.php
@extends('layout')

@section('content')
    <article class="content dashboard-page">
        <div class="title-block">
            <h1 class="title"> Static Tables </h1>
            <p class="title-description"> When blocks aren't enough </p>
        </div>
        <section class="section">
            @foreach($link->diffs->take(1) as $diff)
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-block">
                                <div class="card-title-block">
                                    <h3 class="title"> shoduje se z {{ round($diff->similarity*100, 3) }}%, rozdílný z {{ round($diff->difference*100, 3) }}%</h3>
                                </div>
                                <section class="example">
                                    {!! base64_decode($diff->diff) !!}
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </section>
    </article>
@endsection